module.exports = {
    "api": {
        "results": 24,
        "teams": [
            {
                "team_id": 1169,
                "name": "Honka",
                "code": null,
                "logo": "https://media.api-football.com/teams/1169.png",
                "country": "Finland",
                "founded": 1957,
                "venue_name": "Tapiolan Urheilupuisto",
                "venue_surface": "grass",
                "venue_address": "Urheilupuistontie 2",
                "venue_city": "Esbo",
                "venue_capacity": 5500
            },
            {
                "team_id": 1172,
                "name": "HIFK Elsinki",
                "code": null,
                "logo": "https://media.api-football.com/teams/1172.png",
                "country": "Finland",
                "founded": 1897,
                "venue_name": "Telia 5G -areena",
                "venue_surface": "artificial turf",
                "venue_address": "Urheilukatu 1",
                "venue_city": "Helsinki",
                "venue_capacity": 10770
            },
            {
                "team_id": 649,
                "name": "HJK helsinki",
                "code": null,
                "logo": "https://media.api-football.com/teams/649.png",
                "country": "Finland",
                "founded": 1907,
                "venue_name": "Telia 5G -areena",
                "venue_surface": "artificial turf",
                "venue_address": "Urheilukatu 1",
                "venue_city": "Helsinki",
                "venue_capacity": 10770
            },
            {
                "team_id": 1168,
                "name": "Turku PS",
                "code": null,
                "logo": "https://media.api-football.com/teams/1168.png",
                "country": "Finland",
                "founded": 1922,
                "venue_name": "Paavo Nurmi Stadion",
                "venue_surface": "grass",
                "venue_address": "Paavo Nurmen puistotie 11",
                "venue_city": "Turku",
                "venue_capacity": 13000
            },
            {
                "team_id": 1166,
                "name": "FC Lahti",
                "code": null,
                "logo": "https://media.api-football.com/teams/1166.png",
                "country": "Finland",
                "founded": 1996,
                "venue_name": "Lahden Stadion",
                "venue_surface": "grass",
                "venue_address": "Salpausselänkatu 2",
                "venue_city": "Lahti",
                "venue_capacity": 14465
            },
            {
                "team_id": 1163,
                "name": "Ilves Tampere",
                "code": null,
                "logo": "https://media.api-football.com/teams/1163.png",
                "country": "Finland",
                "founded": null,
                "venue_name": "Tammelan Stadion",
                "venue_surface": "grass",
                "venue_address": "Tammelankatu / Kalevan Puistotie 21",
                "venue_city": "Tampere",
                "venue_capacity": 5060
            },
            {
                "team_id": 1167,
                "name": "Rops",
                "code": null,
                "logo": "https://media.api-football.com/teams/1167.png",
                "country": "Finland",
                "founded": 1950,
                "venue_name": "Rovaniemen Keskuskenttä",
                "venue_surface": "artificial turf",
                "venue_address": "Poromiehentie 2",
                "venue_city": "Rovaniemi",
                "venue_capacity": 4768
            },
            {
                "team_id": 689,
                "name": "SJK",
                "code": null,
                "logo": "https://media.api-football.com/teams/689.png",
                "country": "Finland",
                "founded": null,
                "venue_name": "OmaSP Stadion",
                "venue_surface": "artificial turf",
                "venue_address": "Alaseinäjoenkatu 9",
                "venue_city": "Seinäjoki",
                "venue_capacity": 6000
            },
            {
                "team_id": 2078,
                "name": "EIF",
                "code": null,
                "logo": "https://media.api-football.com/teams/2078.png",
                "country": "Finland",
                "founded": 1905,
                "venue_name": "Ekenäs Centrumplan",
                "venue_surface": "artificial turf",
                "venue_address": "Panimokatu 14, Ekenäs",
                "venue_city": "Tammisaari",
                "venue_capacity": 2500
            },
            {
                "team_id": 2082,
                "name": "IF Gnistan",
                "code": null,
                "logo": "https://media.api-football.com/teams/2082.png",
                "country": "Finland",
                "founded": null,
                "venue_name": "Mustapekka Areena",
                "venue_surface": "artificial turf",
                "venue_address": "Käskynhaltijantie 11",
                "venue_city": "Helsinki",
                "venue_capacity": 2500
            },
            {
                "team_id": 2080,
                "name": "haka",
                "code": null,
                "logo": "https://media.api-football.com/teams/2080.png",
                "country": "Finland",
                "founded": 1934,
                "venue_name": "Tehtaan kenttä",
                "venue_surface": "grass",
                "venue_address": "Tehtaankatu 7",
                "venue_city": "Valkeakoski",
                "venue_capacity": 3516
            },
            {
                "team_id": 1165,
                "name": "KuPS",
                "code": null,
                "logo": "https://media.api-football.com/teams/1165.png",
                "country": "Finland",
                "founded": 1923,
                "venue_name": "Savon Sanomat Areena",
                "venue_surface": "artificial turf",
                "venue_address": "Kaartokatu 6",
                "venue_city": "Kuopio",
                "venue_capacity": 4700
            },
            {
                "team_id": 9175,
                "name": "MP",
                "code": null,
                "logo": "https://media.api-football.com/teams/9175.png",
                "country": "Finland",
                "founded": 1929,
                "venue_name": "Mikkelin Urheilupuisto",
                "venue_surface": "grass",
                "venue_address": "Nuijamiestenkatu 1",
                "venue_city": "Mikkeli",
                "venue_capacity": 7000
            },
            {
                "team_id": 2243,
                "name": "MyPa",
                "code": null,
                "logo": "https://media.api-football.com/teams/2243.png",
                "country": "Finland",
                "founded": 1947,
                "venue_name": "Kymenlaakson Sähkö Stadion",
                "venue_surface": "artificial turf",
                "venue_address": "Kisatie 1",
                "venue_city": "Myllykoski",
                "venue_capacity": 4167
            },
            {
                "team_id": 2081,
                "name": "KPV Kokkola",
                "code": null,
                "logo": "https://media.api-football.com/teams/2081.png",
                "country": "Finland",
                "founded": 1930,
                "venue_name": "Kokkolan Keskuskenttä",
                "venue_surface": "grass",
                "venue_address": "Antti Chydeniuksenkatu 71 / Kustaa Aadolfinkatu",
                "venue_city": "Kokkola",
                "venue_capacity": 3000
            },
            {
                "team_id": 2077,
                "name": "AC oulu",
                "code": null,
                "logo": "https://media.api-football.com/teams/2077.png",
                "country": "Finland",
                "founded": 2002,
                "venue_name": "Raatin stadion",
                "venue_surface": "grass",
                "venue_address": "Raatintie 2, Koskikeskus",
                "venue_city": "Oulu",
                "venue_capacity": 6996
            },
            {
                "team_id": 1164,
                "name": "Inter Turku",
                "code": null,
                "logo": "https://media.api-football.com/teams/1164.png",
                "country": "Finland",
                "founded": 1990,
                "venue_name": "Veritas Stadion",
                "venue_surface": "grass",
                "venue_address": "Hippoksentie 6",
                "venue_city": "Åbo",
                "venue_capacity": 9372
            },
            {
                "team_id": 587,
                "name": "IFK Mariehamn",
                "code": null,
                "logo": "https://media.api-football.com/teams/587.png",
                "country": "Finland",
                "founded": 1935,
                "venue_name": "Wiklöf Holding Arena",
                "venue_surface": "grass",
                "venue_address": "Idrottsgatan",
                "venue_city": "Mariehamn, Ahvenanmaa (Åland",
                "venue_capacity": 5637
            },
            {
                "team_id": 2075,
                "name": "FF Jaro",
                "code": null,
                "logo": "https://media.api-football.com/teams/2075.png",
                "country": "Finland",
                "founded": 1965,
                "venue_name": "Jakobstads Centralplan (Pietarsaaren Keskuskenttä)",
                "venue_surface": "grass",
                "venue_address": "Sodermalmsgatan 20 / Pietarinpuistikko",
                "venue_city": "Jacobstad",
                "venue_capacity": 4600
            },
            {
                "team_id": 2084,
                "name": "AC Kajaani",
                "code": null,
                "logo": "https://media.api-football.com/teams/2084.png",
                "country": "Finland",
                "founded": 2006,
                "venue_name": "Kajaanin liikuntapuisto",
                "venue_surface": "artificial turf",
                "venue_address": "Lönnrotinkatu 1",
                "venue_city": "Kajaani",
                "venue_capacity": 1200
            },
            {
                "team_id": 650,
                "name": "vaasa PS",
                "code": null,
                "logo": "https://media.api-football.com/teams/650.png",
                "country": "Finland",
                "founded": 1924,
                "venue_name": "Elisa Stadion",
                "venue_surface": "grass",
                "venue_address": "Rantamaantie",
                "venue_city": "Vaasa",
                "venue_capacity": 6000
            },
            {
                "team_id": 9198,
                "name": "SJK Akatemia",
                "code": null,
                "logo": "https://media.api-football.com/teams/9198.png",
                "country": "Finland",
                "founded": null,
                "venue_name": null,
                "venue_surface": null,
                "venue_address": null,
                "venue_city": null,
                "venue_capacity": null
            },
            {
                "team_id": 2245,
                "name": "Musa",
                "code": null,
                "logo": "https://media.api-football.com/teams/2245.png",
                "country": "Finland",
                "founded": 1960,
                "venue_name": "Musan kenttä",
                "venue_surface": "grass",
                "venue_address": "Tommilantie 18-20",
                "venue_city": "Pori",
                "venue_capacity": 700
            },
            {
                "team_id": 2076,
                "name": "Kooteepee",
                "code": null,
                "logo": "https://media.api-football.com/teams/2076.png",
                "country": "Finland",
                "founded": 1927,
                "venue_name": "Arto Tolsa Areena",
                "venue_surface": "grass",
                "venue_address": "Korkeavuorenkatu 2",
                "venue_city": "Kotka",
                "venue_capacity": 4780
            }
        ]
    }
}